name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set Version
      run: echo "PACKAGE_VERSION=$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.0.2
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5 

      
    - name: Restore dependencies
      run: nuget restore source/OctoFX.sln
      
    - name: Build
      run: msbuild source/OctoFX.sln  /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile -verbosity:quiet

    - name: Create artifacts folder
      run: |
        mkdir "$GITHUB_WORKSPACE/artifacts"
        mkdir "$GITHUB_WORKSPACE/artifacts/OctopusSamples.OctoFX.Database"
        mkdir "$GITHUB_WORKSPACE/artifacts/OctopusSamples.OctoFX.RateService"
        mkdir "$GITHUB_WORKSPACE/artifacts/OctopusSamples.OctoFX.TradingWebsite"
        
    - name: Install Octopus CLI
      uses: OctopusDeploy/install-octocli@v1
      with:
        version: 7.4.2
    - name: Package OctoFX.Database
      run: |
        octo pack --id="OctoFX.Database" --format="Zip" --version="$PACKAGE_VERSION" --basePath="$GITHUB_WORKSPACE/artifacts/OctopusSamples.OctoFX.Database" --outFolder="$GITHUB_WORKSPACE/artifacts"
    - name: Package OctoFX.TradingWebsite
      run: |
        octo pack --id="OctoFX.TradingWebsite" --format="Zip" --version="$PACKAGE_VERSION" --basePath="$GITHUB_WORKSPACE/artifacts/OctopusSamples.OctoFX.TradingWebsite" --outFolder="$GITHUB_WORKSPACE/artifacts"
    - name: Package OctoFX.RateService
      run: octo pack --id="OctoFX.RateService" --format="Zip" --version="$PACKAGE_VERSION" --basePath="$GITHUB_WORKSPACE/artifacts/OctopusSamples.OctoFX.RateService" --outFolder="$GITHUB_WORKSPACE/artifacts"
    
    - name: Push OctoFX Database
      run: |
        octo push --package="$GITHUB_WORKSPACE/artifacts/OctoFX.Database.$PACKAGE_VERSION.zip" --server="${{ secrets.OCTOPUSSERVERURL }}" --apiKey="${{ secrets.OCTOPUSSERVERAPIKEY }}" --space="${{ secrets.OCTOPUSSERVER_SPACE }}"



