name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set Version
      run: echo "PACKAGE_VERSION=$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.0.2
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5 

    - name: Restore dependencies
      run: nuget restore source/OctoFX.sln
      
          
    - name: Install Octopus CLI
      uses: OctopusDeploy/install-octocli@v1
      with:
        version: 7.4.2    
         
    - name: Build
       ##run: msbuild source/OctoFX.TradingWebsite/OctoFX.TradingWebsite.csproj  /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile /p:RunOctoPack=true /p:Verbocity=quet
      run: msbuild source/OctoFX.sln  /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile /p:RunOctoPack=true /p:Verbocity=quet
   
      
    - name: Push OctoFX TradingWebsite
      run: |
        octo push --package="source/OctoFX.TradingWebsite/obj/octopacked/OctoFX.TradingWebsite.1.0.0.0.nupkg" --overwrite-mode=OverwriteExisting --server="${{ secrets.OCTOPUSSERVERURL }}" --apiKey="${{ secrets.OCTOPUSSERVERAPIKEY }}" --space="${{ secrets.OCTOPUSSERVER_SPACE }}"

    - name: Push OctoFX RateService
      run: |
        octo push --package="source/OctoFX.RateService/obj/octopacked/OctoFX.RateService.1.0.0.0.nupkg" --overwrite-mode=OverwriteExisting --server="${{ secrets.OCTOPUSSERVERURL }}" --apiKey="${{ secrets.OCTOPUSSERVERAPIKEY }}" --space="${{ secrets.OCTOPUSSERVER_SPACE }}"

    - name: Push OctoFX Database
      run: |
        octo push --package="source/OctoFX.Database/obj/octopacked/OctoFX.Database.1.0.0.0.nupkg" --overwrite-mode=OverwriteExisting --server="${{ secrets.OCTOPUSSERVERURL }}" --apiKey="${{ secrets.OCTOPUSSERVERAPIKEY }}" --space="${{ secrets.OCTOPUSSERVER_SPACE }}"



   
   
