name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set Version
      run: echo "PACKAGE_VERSION=$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.0.2
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5 
      
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 4.5
      
    - name: Restore dependencies
      run: nuget restore source/OctoFX.sln
    - name: Build
      run: msbuild source/OctoFX.sln  /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile -verbosity:quiet

    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Create artifacts folder
      run: |
        mkdir "$GITHUB_WORKSPACE/artifacts"
        mkdir "$GITHUB_WORKSPACE/artifacts/OctopusSamples.OctoFX.Database"
        mkdir "$GITHUB_WORKSPACE/artifacts/OctopusSamples.OctoFX.RateService"
        mkdir "$GITHUB_WORKSPACE/artifacts/OctopusSamples.OctoFX.TradingWebsite"

