name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set Version
      run: echo "PACKAGE_VERSION=$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.0.2
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5 

      
    - name: Restore dependencies
      run: nuget restore source/OctoFX.sln
      
  
    - name: Create artifacts folder
      env: 
        NUSPEC_FILE_NAME: "package.nuspec"
      
      run: |
        mkdir "$GITHUB_WORKSPACE/artifacts"
        mkdir "$GITHUB_WORKSPACE/artifacts/OctoFX.Database"
        mkdir "$GITHUB_WORKSPACE/artifacts/OctoFX.RateService"
        mkdir "$GITHUB_WORKSPACE/artifacts/OctoFX.TradingWebsite"
          
        
    - name: Install Octopus CLI
      uses: OctopusDeploy/install-octocli@v1
      with:
        version: 7.4.2    
         
    - name: Build
      run: msbuild source/OctoFX.TradingWebsite/OctoFX.TradingWebsite.csproj  /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile /p:RunOctoPack=true
      ##run: msbuild source/OctoFX.sln  /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile /p:RunOctoPack=true
    - name: Package OctoFX.TradingWebsite
      run: |
        octo pack --id="OctoFX.TradingWebsite" --outFolder="$GITHUB_WORKSPACE/artifacts/OctoFX.TradingWebsite"  --version="1.0.0.3" --basePath="source\OctoFX.TradingWebsite"
 
    - name: Push OctoFX TradingWebsite
      run: |
        octo push --package="$GITHUB_WORKSPACE/artifacts/OctoFX.TradingWebsite.1.0.0.3.nupkg" --overwrite-mode=IgnoreIfExists --server="${{ secrets.OCTOPUSSERVERURL }}" --apiKey="${{ secrets.OCTOPUSSERVERAPIKEY }}" --space="${{ secrets.OCTOPUSSERVER_SPACE }}"

    - name: Package OctoFX.Database
      run: |
        octo pack --id="OctoFX.Database" --outFolder="$GITHUB_WORKSPACE/artifacts"  --version=1.0.0.2 --basePath="source\OctoFX.Database"
        
    - name: Push OctoFX Database
      run: |
        octo push --package="$GITHUB_WORKSPACE/artifacts/OctoFX.Database.1.0.0.2.nupkg" --overwrite-mode=IgnoreIfExists --server="${{ secrets.OCTOPUSSERVERURL }}" --apiKey="${{ secrets.OCTOPUSSERVERAPIKEY }}" --space="${{ secrets.OCTOPUSSERVER_SPACE }}"

    - name: Package OctoFX.RateService
      run: |
        octo pack --id="OctoFX.RateService" --outFolder="$GITHUB_WORKSPACE/artifacts"  --version=1.0.0.2
        
    - name: Push OctoFX RateService
      run: |
        octo push --package="$GITHUB_WORKSPACE/artifacts/OctoFX.RateService.1.0.0.2.nupkg" --overwrite-mode=IgnoreIfExists --server="${{ secrets.OCTOPUSSERVERURL }}" --apiKey="${{ secrets.OCTOPUSSERVERAPIKEY }}" --space="${{ secrets.OCTOPUSSERVER_SPACE }}"

   
        
   


